"""S&P 500 advance/decline breadth from a constituent list.

For every trading day it counts how many stocks in sp500_tickers.csv closed
up vs. the prior day and how many closed down, records which tickers were in
each group, computes net advances (up - down) and a 200-day moving average
of that net number.

Outputs:
  sp500_breadth_daily.csv   one row per day: counts, net, MA, A/D line, ticker lists
  sp500_breadth_ad.pine     TradingView indicator with the results embedded

Usage:
  pip install yfinance pandas
  python sp500_breadth.py                  # download from Yahoo and build everything
  python sp500_breadth.py --ma 200 --years 3
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TICKERS_CSV = HERE / "sp500_tickers.csv"
DAILY_CSV = HERE / "sp500_breadth_daily.csv"
PINE_OUT = HERE / "sp500_breadth_ad.pine"


def load_tickers(path=TICKERS_CSV):
    return pd.read_csv(path)["Symbol"].dropna().str.strip().tolist()


def download_closes(tickers, years):
    import yfinance as yf

    # Yahoo uses "-" for share classes (BRK.B -> BRK-B)
    yahoo = {t: t.replace(".", "-") for t in tickers}
    data = yf.download(list(yahoo.values()), period=f"{years}y", interval="1d",
                       auto_adjust=False, group_by="column", progress=False, threads=True)
    closes = data["Close"].rename(columns={v: k for k, v in yahoo.items()})
    missing = [t for t in tickers if t not in closes or closes[t].dropna().empty]
    if missing:
        print(f"WARNING: no data for {len(missing)} tickers: {', '.join(missing)}", file=sys.stderr)
    return closes.drop(columns=[c for c in missing if c in closes])


def compute_breadth(closes, ma_len=200):
    """closes: DataFrame indexed by date, one column per ticker."""
    closes = closes.sort_index()
    change = closes.diff()
    # A stock only counts on days it has a close today and yesterday
    valid = closes.notna() & closes.shift().notna()
    up = (change > 0) & valid
    down = (change < 0) & valid
    unch = (change == 0) & valid

    out = pd.DataFrame({
        "advancers": up.sum(axis=1),
        "decliners": down.sum(axis=1),
        "unchanged": unch.sum(axis=1),
    })
    out["net"] = out["advancers"] - out["decliners"]
    out = out[valid.any(axis=1)]  # drop the first day (no prior close)
    out[f"net_ma{ma_len}"] = out["net"].rolling(ma_len).mean().round(2)
    out["ad_line"] = out["net"].cumsum()

    cols = closes.columns.to_numpy()
    out["up_tickers"] = [" ".join(cols[row]) for row in up.loc[out.index].to_numpy()]
    out["down_tickers"] = [" ".join(cols[row]) for row in down.loc[out.index].to_numpy()]
    out.index = pd.to_datetime(out.index).date
    out.index.name = "date"
    return out


def _pine_array(name, kind, values, chunk=100):
    """Emit a Pine array built from chunks to stay under per-call argument limits."""
    parts = [values[i:i + chunk] for i in range(0, len(values), chunk)]
    lines = [f"var {name} = array.new<{kind}>()", "if barstate.isfirst"]
    for p in parts:
        lines.append(f"    {name}.concat(array.from({', '.join(p)}))")
    return "\n".join(lines)


def write_pine(breadth, ma_len, path=PINE_OUT, max_days=1500):
    df = breadth.dropna(subset=[f"net_ma{ma_len}"]).tail(max_days)
    dates = [d.strftime("%Y%m%d") for d in df.index]
    adv = [str(int(v)) for v in df["advancers"]]
    dec = [str(int(v)) for v in df["decliners"]]
    ma = [f"{v:.2f}" for v in df[f"net_ma{ma_len}"]]
    first, last = df.index[0], df.index[-1]

    pine = f"""//@version=6
// Generated by sp500_breadth.py — data {first} to {last} ({len(df)} days).
// Re-run the script and paste the new version to update.
// Net = S&P 500 stocks up on the day minus stocks down; MA = {ma_len}-day SMA of Net.
indicator("S&P 500 Net Advances + {ma_len}D MA", shorttitle = "SPX Net A/D", overlay = false)

showHist = input.bool(true, "Show daily net histogram")
showMa   = input.bool(true, "Show {ma_len}-day MA of net")
showZero = input.bool(true, "Show zero line")
bullCol  = input.color(#26a69a, "Up color")
bearCol  = input.color(#ef5350, "Down color")
maCol    = input.color(color.orange, "MA color")

{_pine_array("dates", "int", dates)}
{_pine_array("adv", "int", adv)}
{_pine_array("dec", "int", dec)}
{_pine_array("ma", "float", ma)}

// Look up this bar's date (exchange time zone) in the embedded data
key = year * 10000 + month * 100 + dayofmonth
idx = timeframe.isdaily ? dates.binary_search(key) : -1
has = idx >= 0

a   = has ? adv.get(idx) : na
d   = has ? dec.get(idx) : na
net = has ? a - d : na
m   = has ? ma.get(idx) : na

plot(showHist ? net : na, "Net advances", style = plot.style_columns,
     color = net >= 0 ? color.new(bullCol, 40) : color.new(bearCol, 40))
plot(showMa ? m : na, "{ma_len}D MA of net", color = maCol, linewidth = 2)
hline(showZero ? 0 : na, "Zero", color = color.gray, linestyle = hline.style_dashed)
plot(a, "Advancers", display = display.data_window)
plot(d, "Decliners", display = display.data_window)

var table tbl = table.new(position.top_right, 2, 4, border_width = 1)
if barstate.islast
    lastIdx = dates.size() - 1
    lastNet = adv.get(lastIdx) - dec.get(lastIdx)
    lastMa  = ma.get(lastIdx)
    table.cell(tbl, 0, 0, "As of " + str.tostring(dates.get(lastIdx)), text_color = chart.fg_color, text_size = size.small)
    table.cell(tbl, 1, 0, "")
    table.cell(tbl, 0, 1, "Up / Down", text_color = chart.fg_color, text_size = size.small)
    table.cell(tbl, 1, 1, str.tostring(adv.get(lastIdx)) + " / " + str.tostring(dec.get(lastIdx)), text_color = chart.fg_color, text_size = size.small)
    table.cell(tbl, 0, 2, "Net", text_color = chart.fg_color, text_size = size.small)
    table.cell(tbl, 1, 2, str.tostring(lastNet), text_color = lastNet >= 0 ? bullCol : bearCol, text_size = size.small)
    table.cell(tbl, 0, 3, "{ma_len}D MA", text_color = chart.fg_color, text_size = size.small)
    table.cell(tbl, 1, 3, str.tostring(lastMa, "#.##"), text_color = lastMa >= 0 ? bullCol : bearCol, text_size = size.small)
    if not timeframe.isdaily
        table.cell(tbl, 0, 0, "Switch chart to 1D", text_color = bearCol, text_size = size.small)

alertcondition(ta.crossover(net, m), "Net crossed above MA", "S&P 500 net advances crossed above the {ma_len}-day MA")
alertcondition(ta.crossunder(net, m), "Net crossed below MA", "S&P 500 net advances crossed below the {ma_len}-day MA")
"""
    path.write_text(pine)
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ma", type=int, default=200, help="moving average length in trading days")
    ap.add_argument("--years", type=int, default=3, help="years of history to download")
    ap.add_argument("--pine-days", type=int, default=1500, help="max days embedded in the Pine script")
    args = ap.parse_args()

    tickers = load_tickers()
    print(f"Downloading {len(tickers)} tickers...")
    closes = download_closes(tickers, args.years)
    breadth = compute_breadth(closes, args.ma)
    breadth.to_csv(DAILY_CSV)
    write_pine(breadth, args.ma, max_days=args.pine_days)

    last = breadth.iloc[-1]
    print(f"\n{breadth.index[-1]}: {last.advancers} up, {last.decliners} down, "
          f"{last.unchanged} unchanged -> net {last.net:+d}, {args.ma}D MA {last[f'net_ma{args.ma}']}")
    print(f"Down today: {last.down_tickers}")
    print(f"\nWrote {DAILY_CSV.name} and {PINE_OUT.name}")


if __name__ == "__main__":
    main()
